const URL_TECHNOLOGIES = process.env.NEXT_PUBLIC_API_TECHNOLOGIES;
const URL_GITHUB       = process.env.NEXT_PUBLIC_API_GITHUB;
const URL_ICONS        = process.env.NEXT_PUBLIC_API_ICONS;

export { URL_TECHNOLOGIES, URL_GITHUB, URL_ICONS };
